scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'consul'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: '${CONSUL_URL:-127.0.0.1:8500}'
        services: ['ADMIN']
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

  # mysql
  - job_name: 'mysql metrics'
    dns_sd_configs:
      - names:
          - mysqld-exporter
        refresh_interval: 15s
        type: A
        port: 9104

  # hosts
  - job_name: 'hosts metrics'
    dns_sd_configs:
      - names:
          - node-exporter
        refresh_interval: 15s
        type: A
        port: 9100
  # docker
  - job_name: 'docker metrics'
    dns_sd_configs:
      - names:
          - cadvisor
        refresh_interval: 15s
        type: A
        port: 8080
