# Scrape configuration for default Cinnamon Prometheus HTTP Server on localhost
scrape_configs:
  - job_name: 'cinnamon'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.2.67:9001']
#  - job_name: 'cinnamon'
#    dns_sd_configs:
#      - names:
#          - exercise
#        refresh_interval: 15s
#        type: A
#        port: 9001
