version: '2'
services:
  kib01:
    image: registry.homelab.org/kibana:7.7.0
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
      ELASTICSEARCH_URL: http://es01:9200
    ports:
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true
  es01:
    image: registry.homelab.org/elasticsearch:7.7.0
    environment:
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      bootstrap.memory_lock: 'true'
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: es-docker-cluster
      discovery.seed_hosts: es02,es03
      node.name: es01
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - /home/hanrw/elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
    - 9200:9200/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true
  es03:
    image: registry.homelab.org/elasticsearch:7.7.0
    environment:
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      bootstrap.memory_lock: 'true'
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: es-docker-cluster
      discovery.seed_hosts: es01,es02
      node.name: es03
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - /home/hanrw/elasticsearch/data03:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true
  es02:
    image: registry.homelab.org/elasticsearch:7.7.0
    environment:
      ES_JAVA_OPTS: -Xms6g -Xmx6g
      bootstrap.memory_lock: 'true'
      cluster.initial_master_nodes: es01,es02,es03
      cluster.name: es-docker-cluster
      discovery.seed_hosts: es01,es03
      node.name: es02
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - /home/hanrw/elasticsearch/data02:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: application=true

